name: ai_farmer_mobile
description: Offline-first farmer companion.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.0
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  flutter_riverpod: ^2.5.1
  camera: ^0.10.5+9
  image_picker: ^1.0.8
  tflite: ^1.1.2
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.23
  path_provider: ^2.1.3
  geolocator: ^12.0.0
  speech_to_text: ^6.6.1
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/model/